services:
  database:
    container_name: wikinetes-database
    image: mongo
    networks:
      - wikinetes

  database-init-container:
    container_name: wikinetes-database-init-container
    build: ./database
    restart: no
    depends_on:
      - database   
    networks:
      - wikinetes

  backend:
    build: ./backend
    networks:
      - wikinetes
    depends_on:
      - database
    deploy:
      replicas: 3

  backend-loadbalancer:
    container_name: wikinetes-backend-loadbalancer
    build: ./nginx/backend-loadbalancer
    depends_on:
      - backend
    networks:
      - wikinetes

  frontend:
    build: ./frontend
    depends_on:
      - backend
      - backend-loadbalancer
    networks:
      - wikinetes
    deploy:
      replicas: 3

  frontend-loadbalancer:
    container_name: wikinetes-frontend-loadbalancer
    build: ./nginx/frontend-loadbalancer
    depends_on:
      - frontend
    networks:
      - wikinetes

  reverse-proxy:
    container_name: wikinetes-reverse-proxy
    build: ./nginx/reverse-proxy
    ports:
      - 80:80
    depends_on:
      - backend-loadbalancer
      - frontend-loadbalancer
    networks:
      - wikinetes

networks:
  wikinetes:
    name: wikinetes